-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 14:02:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` INT NOT NULL,
  `documento` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `domicilio` VARCHAR(32) NOT NULL,
  `edad` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `telefono` INT NOT NULL,
  `extension_de_otro` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `id` INT NOT NULL,
  `cuit` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `domicilio` VARCHAR(255) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `proveedor` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `proveedor`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`orden_alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_alquiler` (
  `cliente_id` INT NOT NULL,
  `libros_id` INT NOT NULL,
  `fecha_alquiler` DATETIME NOT NULL,
  PRIMARY KEY (`cliente_id`, `libros_id`),
  INDEX `fk_user_has_libros_libros1_idx` (`libros_id` ASC) VISIBLE,
  INDEX `fk_user_has_libros_user1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_libros_user1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_libros_libros1`
    FOREIGN KEY (`libros_id`)
    REFERENCES `mydb`.`libros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
